Algoritmo "exercicio 7"
// Descrição   :   dizer se este numero esta no intervalo entre 100 e 200
// Autor(a)    :  Gabriel Araujo Pereira
// Data atual  : 24/05/2023
Var
numero:real

Inicio
//entrada
escreval("Digite o numero")
leia(numero)


//processamento
 se (numero> 100) E (numero< 200) entao
  escreval("Este numero ESTÁ no intervalo entre 100 e 200")
 senao
  escreval("Este numero NÃO está no intervalo entre 100 e 200")
 fimse

Fimalgoritmo