algoritmo "Exercicio 1"
// Função :  dizer se o número é maior que 10
// Autor : Gabriel Araujo Pereira
// Data : 18/05/2023
// Seção de Declarações 
var
numero:real

inicio
//entrada

escreval("Digite o número")
leia (numero)

//processamento

se numero > 10 entao
  escreval("Este número é maior que 10")
senao
  escreval("Este número não é maior que 10")
fimse
// Seção de Comandos 
fimalgoritmo

