algoritmo "Exercicio 2"
// Função :  dizer como esta o saldo do cliente
// Autor : Gabriel Araujo Pereira
// Data : 18/05/2023
// Seção de Declarações 
var
sal,gasto:real

inicio
//entrada

escreval("Digite o seu salario")
leia (sal)
escreval("Digite o valor gasto")
leia (gasto)

//processamento

se gasto > sal entao
  escreval("O seu saldo está negativo")
senao
  escreval("O seu saldo está positivo")
fimse
// Seção de Comandos 
fimalgoritmo

