algoritmo "Exercicio 3"
// Função :  dizer se é maior ou menor de idade
// Autor : Gabriel Araujo Pereira
// Data : 18/05/2023
// Seção de Declarações 
var
idade:inteiro
nome: caractere

inicio
//entrada

escreval("Digite o seu nome")
leia (nome)
escreval("Digite a sua idade")
leia (idade)

//processamento

se idade >=18 entao
  escreval(nome, "você é maior de idade")
senao
  escreval(nome, " você ainda é menor de idade")
fimse
// Seção de Comandos 
fimalgoritmo

